### ISSUE TITLE
Connection failure with Node 0.12

### ISSUE THREAD

**Issue by reality** [prawnsalad/KiwiIRC#705]
Getting this error upon SSL connection to server: 

```
2015-05-01 12:27:52 - error: [Uncaught exception] TypeError: Cannot read property 'toString' of undefined stack=TypeError: Cannot read property 'toString' of undefined
    at rawSocketConnect (/home/node/KiwiIRC/server/irc/connection.js:688:86)
    at TLSSocket.<anonymous> (/home/node/KiwiIRC/server/irc/connection.js:289:38)
    at TLSSocket.emit (events.js:129:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:991:10)
```

Works fine with Node 0.10, tested on Kiwi development and stable.

**Comment by dateno1** [comment]
maybe kiwi is not support TLS for SSL Connection(it make connection problem with SSL3 disabled IRC Server)

**Comment by prawnsalad** [comment]
Kiwi supports SSL/TLS just fine. @reality, is this still happening on the latest development branch?

**Comment by dateno1** [comment]
How can find version number on kiwi?

it downloaded on Mar.17 2015

ok i will redownload and retest

**Comment by dateno1** [comment]
Now kiwi is Redownload and Reinstalled (it is 0.9.1)

but it same

it say 'connection error (socket hang up)'

and i can't find log (conf.log="/var/log/kiwi.log") (i can't find this file)

ngircd 22.1
CipherList = ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS:!DHE:!kEDH:HIGH:!eNULL:!EXPORT:!DES:!RC4:!PSK:!AECDH:!LOW:!SRP:!ADH:@STRENGTH:!SSLv3
with openssl 1.0.2a (ssl2/3 disabled by compile option) and nodejs 0.12.4 (ssl2/3 disabled by compile option)
