### ISSUE TITLE
KiwiIRC randomly quitting

### ISSUE THREAD

**Issue by ghost** [prawnsalad/KiwiIRC#790]
This happened last night and I reported it to #kiwiirc, I started KiwiIRC again and it has run for around 12 hours until randomly quitting again about 20 minutes ago.

KiwiIRC users disconnected with quit reason 'Read error':

```
2:20 PM ⇐ james quit (james@8238364A.5F77C632.3A052B2E.IP) Read error
2:20 PM ⇐ Heidi quit (Heidi@EEC02881.948FC51B.BC9E9E65.IP) Read error
2:20 PM ⇐ guest58 quit (guest58@46081FF9.4700B6FE.38F07495.IP) Read error
2:20 PM ⇐ bustysharon quit (bustysharo@9AEEE422.496CC97D.8F62661C.IP) Read error
2:20 PM ⇐ Guest_82956 quit (Guest_8295@194A7BEB.18D16FE1.FC7CA9EE.IP) Read error
2:20 PM ⇐ mrbigone quit (mrbigone@71CE433B.B928932B.E01A1172.IP) Read error
2:20 PM ⇐ Fun quit (Fun@8A94100E.B35E37AA.E7E70853.IP) Read error
2:20 PM ⇐ badsanta quit (badsanta@33F35CC4.6DDF494.FA9E8EFC.IP) Read error
2:20 PM ⇐ pete57 quit (pete57@323B13E2.7E3A8DEA.7E9D7157.IP) Read error
2:20 PM ⇐ Katie38NJ quit (Katie38NJ@C6DF402B.CEFB94A2.F510882E.IP) Read error
2:20 PM ⇐ BlackManMaryland quit (BlackManMa@91257B18.779B4F75.26D33BB3.IP) Read error
2:20 PM ⇐ zuperman quit (zuperman@470F2581.ABE504B1.F13C5051.IP) Read error
2:20 PM ⇐ Gail quit (Gail@A2A86A79.672C302.B5DD7732.IP) Read error
2:20 PM ⇐ MALE-34 quit (MALE-34@A2900A27.A2D61B16.1F8ADEF4.IP) Read error
2:20 PM ⇐ Lyds-F-Melb-UK quit (Lyds-F-Mel@D4C3F7A.10E8BDD6.8098F725.IP) Read error
2:20 PM ⇐ kenr quit (kenr@A328F721.C7F7327D.44127BC0.IP) Read error
2:20 PM ⇐ Opie854 quit (Opie854@B7A23957.8930E293.D300A498.IP) Read error
2:20 PM ⇐ GeorgiaM quit (GeorgiaM@40E95935.19F74148.EF6E9260.IP) Read error
2:20 PM ⇐ Lewis quit (Lewis@B2AF99E.4820943B.94EE43BC.IP) Read error
2:20 PM ⇐ Oldergay quit (Oldergay@2F4064EB.EF596C14.64AE2D31.IP) Read error
2:20 PM ⇐ AngelEyes quit (AngelEyes@9D8E1063.9184530.BDDEE505.IP) Read error
2:20 PM ⇐ joe38 quit (joe38@DDE95346.5C0C0D33.BF0FE0F2.IP) Read error
2:20 PM ⇐ OlderGuy quit (OlderGuy@AD9C47E1.CBDCBCF.F99D0D06.IP) Read error
2:20 PM ⇐ Tara quit (Tara@9DB30C0D.4320271B.1337AAA1.IP) Read error
2:20 PM ⇐ Chris_ quit (Chris_@E96A524B.4FC643E4.98FFBA61.IP) Read error
2:20 PM ⇐ LikesBeingNaked quit (LikesBeing@84BF4E8.274836AA.F343EBE7.IP) Read error
2:20 PM ⇐ crissy quit (crissy@5EEDF1D4.99F5E561.FF21B95E.IP) Read error
2:20 PM ⇐ nyvia-lesbiansub quit (nyvia-lesb@F1C83861.4DAC4C1E.D98269B9.IP) Read error
2:20 PM ⇐ gwen quit (gwen@A8A581E9.7AF6E008.30136D20.IP) Read error
2:20 PM ⇐ IndLady quit (IndLady@6F450D2D.9110A47F.C74BB022.IP) Read error
2:20 PM ⇐ William58 quit (William58@5A2CA5B2.A07CFD65.9146F46E.IP) Read error
2:20 PM ⇐ clyde52 quit (clyde52@E28E3551.DFDA5C8.7D42C9D9.IP) Read error
2:20 PM ⇐ m22Aus quit (m22Auslate@3CC221E1.FBD4B249.A8E29D85.IP) Read error
2:20 PM ⇐ JustAlone quit (JustAlone@147C4CC4.7D32D869.4BCBFBD3.IP) Read error
2:20 PM ⇐ RichieRich quit (RichieRich@E212C06.600DDE4A.B1E5BC1A.IP) Read error
2:20 PM ⇐ OnMyKnees quit (OnMyKnees@A1897E53.C82B1CA4.BF5650F.IP) Read error
2:20 PM ⇐ OfficeGuy quit (OfficeGuy@29F8183E.5B37030.74823079.IP) Read error
2:20 PM ⇐ BIGonCAM quit (BIGonCAM@E454DCB4.22FC612E.46916AB5.IP) Read error
2:20 PM ⇐ Bored-Husband4RP quit (Bored-Husb@2A41A75E.171BAE50.758BB6A5.IP) Read error
2:20 PM ⇐ jamesisjames quit (jamesisjam@9A8F52B2.72367436.642FF94C.IP) Read error
2:20 PM ⇐ DIMIS quit (DIMIS@61419C7A.99B027E7.8221925F.IP) Read error
2:20 PM ⇐ Ted quit (Ted@F2625702.D68ED1A5.3DD0305A.IP) Read error
2:20 PM ⇐ Businessman quit (Businessma@CE6A9C73.2B32A713.D5934B24.IP) Read error
2:20 PM ⇐ becky-19-les quit (becky-19-l@BD1F0859.D6F0175B.BBCDD9CB.IP) Read error
2:20 PM ⇐ Mikey quit (Mikey@12A95379.25E6EDE7.EF54740A.IP) Read error
2:20 PM ⇐ blueguy quit (blueguy@37FCE292.B70C6C13.89C3BA4E.IP) Read error
2:20 PM ⇐ amber quit (amber@8ECC88B0.93573C19.2C31D616.IP) Read error
2:20 PM ⇐ Ebony quit (Ebony@8842443F.89C31662.D0FD2F03.IP) Read error
2:20 PM ⇐ noon quit (noon@6E01D159.17AA70D2.24C3D1FF.IP) Read error
2:20 PM ⇐ TylerDurden quit (TylerDurde@DA7A8D4B.C90B1C63.627274C8.IP) Read error
2:20 PM ⇐ Cherry_Pie quit (CherryPie@F24D4042.6D68A7AD.9590C9F.IP) Read error
2:20 PM ⇐ lilDeb quit (lilDeb@238FCB2C.B1736FAB.48ADE0B2.IP) Read error
2:20 PM ⇐ YoungnHung26 quit (YoungnHung@414E4C7E.2895B653.1A625F97.IP) Read error
2:20 PM ⇐ MarriedMom quit (MarriedMom@7A541A1A.2489F5FD.4669388B.IP) Read error
...
```

KiwiIRC at that point was not running, so I restarted, log shows just hundreds of these lines:

```
root@localhost:~/KiwiIRC-0.9.2# tail kiwi.log 
2015-11-27 14:20:00 - warn: irc_connection error (127.0.0.1): Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
2015-11-27 14:20:00 - warn: irc_connection error (127.0.0.1): Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
2015-11-27 14:20:00 - warn: irc_connection error (127.0.0.1): Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
root@localhost:~/KiwiIRC-0.9.2# 
```

**Comment by kiwier1** [comment]
same problem again, KiwiIRC been down since mid night, switching back to lightIRC as this seems unstable

**Comment by mestaritonttu** [comment]
There have been massive DDoS attacks this week: https://twitter.com/freenodestaff/status/670162459328684032
Kiwiirc.com web client has refused connections for a few days.

**Comment by kiwier1** [comment]
I'm using our own install and not using Freenode

**Comment by prawnsalad** [comment]
Did the kiwiic process die again? Anything in log files somewhere? Not even syslog? You could try running kiwi in a screen session via `./kiwi -f` and taking note of any output when the process dies. There will be *something* somewhere in a log file explaining what's happening in your case.

**Comment by kiwier1** [comment]
@prawnsalad in kiwi.log is that line I already posted but a lot of that, around 100 per minute! Only other messages are about " Unknown proxy "?

**Comment by prawnsalad** [comment]
Do you mean `Unlisted proxy`? If so, that means that it has seen proxy related HTTP headers from somewhere you have not whitelisted. If you're not using a reverse proxy then it is safe to ignore.

If you can't see anything else in any log files anywhere, then I would try running it via `./kiwi -f` in a screen session. Maybe some output is being spit out there when the process dies.

**Comment by kiwier1** [comment]
@prawnsalad yes sorry, I was on mobile and bad memory, I mean that!

Ok, I started it now in a screen session, will the session keep open even if Kiwi quits again?

Here are the only " errors " so far,

```
info: Listening on 0.0.0.0:7778 without SSL
Request contains invalid range header:  [ '0', '1' ]
[Error: Range request present but invalid, might serve whole file instead]
Request contains invalid range header:  [ '0', '1' ]
[Error: Range request present but invalid, might serve whole file instead]
```

**Comment by kiwier1** [comment]
Another observation, Kiwi uses so much memory!

Currently using 38%, UnrealIRCd is only using 1.2% with 1000's of clients :/

**Comment by kiwier1** [comment]
100's of these now

```
info: Unlisted proxy: 185.26.182.33
info: Unlisted proxy: 185.26.182.33
info: Unlisted proxy: 185.26.182.33
info: Unlisted proxy: 185.26.182.33
info: Unlisted proxy: 185.26.182.33
info: Unlisted proxy: 185.26.182.33
info: Unlisted proxy: 185.26.182.33
info: Unlisted proxy: 185.26.182.33
info: Unlisted proxy: 185.26.182.33
info: Unlisted proxy: 185.26.182.33
info: Unlisted proxy: 185.26.182.33
info: Unlisted proxy: 185.26.182.33
```

**Comment by prawnsalad** [comment]
Any more crashes yet while it's been open in a screen session?

The memory usage will always be higher than unrealircd. Kiwi is built using javascript while unrealircd is in C++. That said, one of the libs kiwi currently uses is a bit of a memory hog so it will be getting replaced in the next major version of Kiwi.
