### ISSUE TITLE
Crash kiwiirc

### ISSUE THREAD

**Issue by sianur63** [prawnsalad/KiwiIRC#818]
Hi, 

I have a problem with that regularly kiwi crash with the error message below

2016-01-23 21:08:23 - warn: irc_connection error (irc.myNetwork.com): Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:763:14)
2016-01-23 21:08:23 - warn: irc_connection error (irc.myNetwork.com): Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:763:14)
2016-01-23 23:33:14 - info: Listening on 0.0.0.0:7779 without SSL

My server use:

Debian 7
Nginx 1.8
npm 3.3.12
node v5.4.1

Thanks

**Comment by prawnsalad** [comment]
They are not crash errors, just warnings.

* How often does it crash
* How many *concurrent* users are connected?
* Have you modified the open file descriptor limit in the OS?

**Comment by sianur63** [comment]
Ils ne sont pas des erreurs accident, de simples avertissements.

He crash randomly. Every 4 or 5 days
Between 20 and 30 users online at crash
I dont nothing change just add fields in the form https://github.com/sianur63/kiwi-discutea

Whats a file descriptor limit in the OS ?

**Comment by prawnsalad** [comment]
The file descriptor limit is how many files (or sockets) can be open at a time from a process. But since you're only seeing around 20-30 users that shouldn't be an issue.

How are checking that kiwi has crashed? Does the process stop entirely? You might want to run kiwi in a screen session, starting kiwi via `./kiwi -f` so that any errors will be seen if it does crash.

**Comment by prawnsalad** [comment]
Did you manage to find what was causing this crash via `./kiwi -f`?

**Comment by tyronec64** [comment]
We have the same actually:

this is what i get when i run ./kiwi -f
and this is allready happening with 10 users

warn: irc_connection error (nirchat1.nr1net.com): Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:763:14)

and this is spammed for every request.

**Comment by sianur63** [comment]
Sorry, I can't start my server ./kiwi -f
