### ISSUE TITLE
"Uncaught exception: Table size bigger than maximum stack" when using Chromium

### ISSUE THREAD

**Issue by jesrui** [prawnsalad/KiwiIRC#913]
I get the following exception when I connect to a Kiwi server using a recent chromium version:

```
$ tail -f kiwi.log 
2016-12-15 08:17:40 - error: [Uncaught exception] Error: Table size bigger than maximum stack=Error: Table size bigger than maximum
    at assert (KiwiIRC/node_modules/hpack.js/lib/hpack/utils.js:3:11)
    at Table.updateSize (KiwiIRC/node_modules/hpack.js/lib/hpack/table.js:82:3)
    at Decompressor.updateTableSize (KiwiIRC/node_modules/hpack.js/lib/hpack/decompressor.js:58:15)
    at Connection._handleSettings (KiwiIRC/node_modules/spdy-transport/lib/spdy-transport/connection.js:465:27)
    at Connection._handleFrame (KiwiIRC/node_modules/spdy-transport/lib/spdy-transport/connection.js:301:10)
    at Parser.<anonymous> (KiwiIRC/node_modules/spdy-transport/lib/spdy-transport/connection.js:149:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at readableAddChunk (KiwiIRC/node_modules/readable-stream/lib/_stream_readable.js:198:18)
    at Parser.Readable.push (KiwiIRC/node_modules/readable-stream/lib/_stream_readable.js:157:10)
```
I get the same exception with master (git commit 6f90124) and development (55b0bb2) branches.

Updating the requirements on the `spdy` module to the latest stable version seems to fix the problem for me:

```$ git diff
diff --git a/package.json b/package.json
index b2be5fe..2ab3e11 100644
--- a/package.json
+++ b/package.json
@@ -25,7 +25,7 @@
     "node-static": "^0.7.7",
     "po2json": "^0.4.1",
     "socksjs": "^0.5.0",
-    "spdy": "^2.0.5",
+    "spdy": "^3.4.4",
     "uglify-js": "^2.4.24",
     "winston": "^1.0.1"
   },
```

### Version information 

- KiwiIRC
  - development   55b0bb2
  - master        6f90124
- chromium 55.0.2883.87 (64-bit)
- node v7.2.1

**Comment by matschi-klickme** [comment]
I'm experiencing this issue as well. 

kiwiirc@0.9.4 ARCH
Chromium 55.0.2883.87
node v7.4.0

**Comment by bug** [comment]
Same issue here. Fixed upgrading spdy.

**Comment by Fizzixnerd** [comment]
Can someone merge this change?  I also did this.

**Comment by prawnsalad** [comment]
@Fizzixnerd will look into changing this but most of the effort is going into https://github.com/kiwiirc/kiwiirc now. If not already, you should take a look at migrating to that new version.
