### ISSUE TITLE
It looks like some connections stand still waiting with the message "connection in progress"

### ISSUE THREAD

**Issue by fmapelli** [prawnsalad/KiwiIRC#941]
Hi,
It's about a month that I couldn't fix my webchat, I think it's something about connections.
It looks like some connections stand still waiting with the message "connection in progress" in the webchat
What can I do to fix this? Here's the log errors:

2017-07-07 07:47:22 - error: [Uncaught exception] Error: read ECONNRESET stack=Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)

2017-07-07 07:48:51 - error: [Uncaught exception] TypeError: Cannot call method 'dispatch' of undefined stack=TypeError: Cannot call method 'dispatch' of undefined
    at parseIrcLine (/var/chat/KiwiIRC/server/irc/connection.js:987:26)
    at processIrcLines (/var/chat/KiwiIRC/server/irc/connection.js:904:9)
    at socketOnData (/var/chat/KiwiIRC/server/irc/connection.js:864:5)
    at Socket.<anonymous> (/var/chat/KiwiIRC/server/irc/connection.js:334:26)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)

**Comment by prawnsalad** [comment]
Well the ECONNRESET error means that the IRC server closed the connection for some reason. Have you checked the IRC servers logs? You can also try running kiwi via `./kiwi -f -v` to see extra debugging output.

I can't reproduce that second error, but take a look at the first issue first to make sure that's not causing it.

**Comment by fmapelli** [comment]
Thank you for answering prawnsalad,
Unfortunately I cannot see errors by taping -v. In 5 minutes I collect logs for 100mb!
It works correctly for 30 minutes, after that the monitor shows "connection in progress"
In this "error phase" I tried to connect with a nickname, but it gives no traces in logs.
It's like it does not accept further connections, but actually there are not so much connections on IRC channel.
I use the latest version of Kiwi, and added proxy nginx.
The resources on the server with kiwi are used at 30% (RAM, CPU).

- maybe there are users stand hanging?
- could it be a problem about connections on the server?

P.S. here's the only part of log looking interesting:
2017-07-07 15:49:50 - debug: (client 5473) Disconnected
2017-07-07 15:49:50 - debug: (client 5473) Disposing
